### ISSUE TITLE
Ask a question about UCL Machine Vision Module

### ISSUE THREAD

**Issue by BinglunWang** [CrystalJYX/UCL_COMP0137_MV#1]
I hope this finds you well.

I am Binglun, an MSc CGVI student at UCL. I am writing to ask you about the past papers on Module Machine Vision COMP0137. I see that you were a student in this module, so I would appreciate it if you could help me with this question.

Recently, I have come to the review stage before the UCL exam. I plan to use past papers to practice the questions. [UCL need to share 3 previous years](https://www.ucl.ac.uk/library/digital-collections/collections/exam/faqs)' questions with students. However, Professor Gabe only shares one last paper with us. May I know if you would like to share past papers, if possible? Also, do you have any suggestions for the review?

Any answers would help me immensely with my study. Thank you very much in advance.

Best wishes,
Binglun

**Comment by CrystalJYX** [comment]
The format of last year's exam was online, which may not be very helpful to you. But if you want, you can ask me on WeChat (ID:Crystal_JXX) or send me email (jyx.jinyuxi@gmail.com). It's hard to start a conversation here.
